version: "2.29.2"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_DATABSE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: Test@123
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "33066:3306"